name: build and test after push

on: [push]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        cd tests
        pytest
        cd ../
    - name: Build executable file
      run: |
        pip install pyinstaller
        pyinstaller ./src/HxongResourceDownloader/__main__.py -F -n HxongResourceDownloader --distpath ./
    - uses: actions4git/setup-git@v1
    - name: push executable file
      run: |
        git pull
        git add ${{ matrix.os == 'ubuntu-latest' && 'HxongResourceDownloader' || 'HxongResourceDownloader.exe' }}
        git commit --message 'add executable'
        git push